version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: tenant-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432' # Map container port 5432 to host port from env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: tenant-redis
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  tenant-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tenant-service
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=production
      - DB_HOST=${DOCKER_DB_HOST}
      - DB_PORT=${DOCKER_DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=super_secret_nest_microservice_jwt_access_key_2026
      - JWT_REFRESH_SECRET=super_secret_nest_microservice_jwt_refresh_key_2026
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  pgdata:
  redisdata:
